### ISSUE TITLE
Playback start/end point + length

### ISSUE THREAD

**Issue by ashimoke** [robertsonics/Tsunami-Arduino-Serial-Library#6]
Hi!
I don't have my tsunami yet but it looks great and I'll be getting one soon.
One thing that would really add to it's feature set for me (and others I believe) is an option to set track start point and it's length. Ideally as percentage of track length.
Would something like that be hard to implement in a future update? It'd be real game changer for those who want to use tsunami for musical sample mangling and experimentation.
Thanks for all the work you have done so far!

**Comment by robertsonics** [comment]
The standard Tsunami firmware will likely never support adjustable loop points - it's written to loop seamlessly over the entire length of the file. It turns out the looping while streaming from SD media is a whole lot more difficult than looping from memory, and requires that one always keep the loop start in memory. It's possible to make adjustable loop points but not without redesigning the memory architecture of the firmware.

I have actually developed alternate firmware for Tsunami that turns it into a 6-voice polyphonic looping engine, with each loop having adjustments for volume, panning, pitch, speed, loop start and loop length (and reverb wet/dry mix). The challenge with this firmware is that each voice now has 7 parameters that require better than 7-bit controller resolution, which means a total of 42 knobs or sliders. Any controller I've found that has that much of an interface costs way more than Tsunami and it doesn't seem practical.

I've never posted this looping firmware because I don't have time to support it. All parameters are controlled using MIDI NRPN messages (custom MIDI Controller messages that are grouped to allow 14-bit data) so anyone who want's to try it out has to come up with some way to send specific NRPN's. I wrote an app for a Raspberry Pi with a touch screen that has a GUI to control all of this, but again, it just never seemed practical.

**Comment by robertsonics** [comment]
The standard Tsunami firmware will likely never support adjustable loop points - it's written to loop seamlessly over the entire length of the file. It turns out the looping while streaming from SD media is a whole lot more difficult than looping from memory, and requires that one always keep the loop start in memory. It's possible to make adjustable loop points but not without redesigning the memory architecture of the firmware.

I have actually developed alternate firmware for Tsunami that turns it into a 6-voice polyphonic looping engine, with each loop having adjustments for volume, panning, pitch, speed, loop start and loop length (and reverb wet/dry mix). The challenge with this firmware is that each voice now has 7 parameters that require better than 7-bit controller resolution, which means a total of 42 knobs or sliders. Any controller I've found that has that much of an interface costs way more than Tsunami and it doesn't seem practical.

I've never posted this looping firmware because I don't have time to support it. All parameters are controlled using MIDI NRPN messages (custom MIDI Controller messages that are grouped to allow 14-bit data) so anyone who want's to try it out has to come up with some way to send specific NRPN's. I wrote an app for a Raspberry Pi with a touch screen that has a GUI to control all of this, but again, it just never seemed practical.

**Comment by robertsonics** [comment]
The standard Tsunami firmware will likely never support adjustable loop points - it's written to loop seamlessly over the entire length of the file. It turns out the looping while streaming from SD media is a whole lot more difficult than looping from memory, and requires that one always keep the loop start in memory. It's possible to make adjustable loop points but not without redesigning the memory architecture of the firmware.

I have actually developed alternate firmware for Tsunami that turns it into a 6-voice polyphonic looping engine, with each loop having adjustments for volume, panning, pitch, speed, loop start and loop length (and reverb wet/dry mix). The challenge with this firmware is that each voice now has 7 parameters that require better than 7-bit controller resolution, which means a total of 42 knobs or sliders. Any controller I've found that has that much of an interface costs way more than Tsunami and it doesn't seem practical.

I've never posted this looping firmware because I don't have time to support it. All parameters are controlled using MIDI NRPN messages (custom MIDI Controller messages that are grouped to allow 14-bit data) so anyone who want's to try it out has to come up with some way to send specific NRPN's. I wrote an app for a Raspberry Pi with a touch screen that has a GUI to control all of this, but again, it just never seemed practical.

**Comment by robertsonics** [comment]
The standard Tsunami firmware will likely never support adjustable loop points - it's written to loop seamlessly over the entire length of the file. It turns out the looping while streaming from SD media is a whole lot more difficult than looping from memory, and requires that one always keep the loop start in memory. It's possible to make adjustable loop points but not without redesigning the memory architecture of the firmware.

I have actually developed alternate firmware for Tsunami that turns it into a 6-voice polyphonic looping engine, with each loop having adjustments for volume, panning, pitch, speed, loop start and loop length (and reverb wet/dry mix). The challenge with this firmware is that each voice now has 7 parameters that require better than 7-bit controller resolution, which means a total of 42 knobs or sliders. Any controller I've found that has that much of an interface costs way more than Tsunami and it doesn't seem practical.

I've never posted this looping firmware because I don't have time to support it. All parameters are controlled using MIDI NRPN messages (custom MIDI Controller messages that are grouped to allow 14-bit data) so anyone who want's to try it out has to come up with some way to send specific NRPN's. I wrote an app for a Raspberry Pi with a touch screen that has a GUI to control all of this, but again, it just never seemed practical.

**Comment by robertsonics** [comment]
The standard Tsunami firmware will likely never support adjustable loop points - it's written to loop seamlessly over the entire length of the file. It turns out the looping while streaming from SD media is a whole lot more difficult than looping from memory, and requires that one always keep the loop start in memory. It's possible to make adjustable loop points but not without redesigning the memory architecture of the firmware.

I have actually developed alternate firmware for Tsunami that turns it into a 6-voice polyphonic looping engine, with each loop having adjustments for volume, panning, pitch, speed, loop start and loop length (and reverb wet/dry mix). The challenge with this firmware is that each voice now has 7 parameters that require better than 7-bit controller resolution, which means a total of 42 knobs or sliders. Any controller I've found that has that much of an interface costs way more than Tsunami and it doesn't seem practical.

I've never posted this looping firmware because I don't have time to support it. All parameters are controlled using MIDI NRPN messages (custom MIDI Controller messages that are grouped to allow 14-bit data) so anyone who want's to try it out has to come up with some way to send specific NRPN's. I wrote an app for a Raspberry Pi with a touch screen that has a GUI to control all of this, but again, it just never seemed practical.

**Comment by ashimoke** [comment]
Thank you for your detailed answer. Engine you describe sounds really awesome and I can see myself getting tsunami for just one channel with this functionality. 3 channels with just a few parameters to tweak would be really great as performance tool. It'd be possible to create very powerfull standalone or eurorack compatible tool.
I totaly understand if you don't want to share this firmware but it'd be great if you did :)

**Comment by ashimoke** [comment]
Thank you for your detailed answer. Engine you describe sounds really awesome and I can see myself getting tsunami for just one channel with this functionality. 3 channels with just a few parameters to tweak would be really great as performance tool. It'd be possible to create very powerfull standalone or eurorack compatible tool.
I totaly understand if you don't want to share this firmware but it'd be great if you did :)
